--  constraints.

ALTER TABLE (`Salaried`)
ADD CONSTRAINT `FK_salaried` FOREIGN KEY (`SalariedID`) REFERENCES `Staff` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`Volunteer`) 
ADD CONSTRAINT `FK_Volunteer` FOREIGN KEY (`StaffID`) REFERENCES `Staff` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`SalariedStaffs`)
ADD CONSTRAINT `FK_SalariedStaffs` FOREIGN KEY (`SalariedStaffID`) REFERENCES `Salaried` (`SalariedID`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_SalariedStaffs2` FOREIGN KEY (`EventBeginTimeStamp`) REFERENCES `Event` (`BeginTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_SalariedStaffs3` FOREIGN KEY (`EventEndTimeStamp`) REFERENCES `Event` (`EndTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_SalariedStaffs4` FOREIGN KEY (`EventVenueName`) REFERENCES `Event` (`VenueName`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`VolunteerStaffs`)
ADD CONSTRAINT `FK_VolunteerStaffs` FOREIGN KEY (`VolunteerStaffID`) REFERENCES `Volunteer` (`StaffID`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_VolunteerStaffs2` FOREIGN KEY (`EventBeginTimeStamp`) REFERENCES `Event` (`BeginTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_VolunteerStaffs3` FOREIGN KEY (`EventEndTimeStamp`) REFERENCES `Event` (`EndTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_VolunteerStaffs4` FOREIGN KEY (`EventVenueName`) REFERENCES `Event` (`VenueName`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`Official`)
ADD CONSTRAINT `FK_Official` FOREIGN KEY (`AccommodationName`) REFERENCES `Room` (`AccommodationName`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_Official2` FOREIGN KEY (`RoomNumber`) REFERENCES `Room` (`RoomNumber`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`TeamSponsor`)
ADD CONSTRAINT `FK_TeamSponsor` FOREIGN KEY (`SponsorName`) REFERENCES `Sponsor` (`Name`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`TeamSponsorship`)
ADD CONSTRAINT `FK_TeamSponsorship` FOREIGN KEY (`TeamSponsorName`) REFERENCES `TeamSponsor` (`SponsorName`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_TeamCountryName` FOREIGN KEY (`TeamCountryName`) REFERENCES  `Team` (`CountryName`) ON UPDATE CASCADE ON  DELETE CASCADE
ADD CONSTRAINT `FK_TeamSportID` FOREIGN KEY (`TeamSportID`) REFERENCES `Team` (`SportID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`EventSponsor`) 
ADD CONSTRAINT `FK_EventSponsor` FOREIGN KEY (`SponsorName`) REFERENCES `Sponsor` (`Name`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`EventSponsorship`)
ADD CONSTRAINT `FK_EventSponsorship` FOREIGN KEY (`EventSponsorName`) REFERENCES `EventSponsor` (`SponsorName`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_BeginTime` FOREIGN KEY (`EventBeginTimeStamp`) REFERENCES `Event` (`BeginTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_EndTime` FOREIGN KEY (`EventEndTimeStamp`) REFERENCES `Event` (`EndTimeStamp`) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT `FK_VenueName` FOREIGN KEY (`EventVenueName`) REFERENCES `Event` (`VenueName`) ON UPDATE CASCADE ON DELETE CASCADE;
