ALTER TABLE (Event)
ADD CONSTRAINT FK_EventSportID FOREIGN KEY SportID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_EventVenueName FOREIGN KEY VenueName REFERENCES Venue (Name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (EventRound)
ADD CONSTRAINT FK_EventRoundBeginTimeStamp FOREIGN KEY BeginTimeStamp REFERENCES Event (BeginTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_EventRoundEndTimeStamp FOREIGN KEY EndTimeStamp REFERENCES Event (EndTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_EventRoundVenueName FOREIGN KEY VenueName REFERENCES Event (VenueName) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Officiates)
ADD CONSTRAINT FK_OfficiatesOfficialID FOREIGN KEY OfficialID REFERENCES Official (ID) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_OfficiatesBeginTimeStamp FOREIGN KEY BeginTimeStamp REFERENCES Official (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Competes)
ADD CONSTRAINT FK_CompetesCountryName FOREIGN KEY CountryName REFERENCES Country (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_CompetesSportID FOREIGN KEY SportID REFERENCES Team (SportID) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_CompetesBeginTimeStamp FOREIGN KEY BeginTimeStamp REFERENCES Event (BeginTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_CompetesEndTimeStamp FOREIGN KEY EndTimeStamp REFERENCES Event (EndTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_CompetesVenueName FOREIGN KEY VenueName REFERENCES Venue (Name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (SportTypes)
ADD CONSTRAINT FK_SportTypesSportID FOREIGN KEY SportID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`Men'sDivision`)
ADD CONSTRAINT `FK_Men'sDivisionID` FOREIGN KEY ID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (`Women'sDivision`)
ADD CONSTRAINT `FK_Women'sDivisionID` FOREIGN KEY ID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (TeamSport)
ADD CONSTRAINT FK_TeamSportID FOREIGN KEY ID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (IndividualSport)
ADD CONSTRAINT FK_IndividualSportID FOREIGN KEY ID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (VenueType)
ADD CONSTRAINT FK_VenueType FOREIGN KEY Name REFERENCES Venue (Name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Athlete)
ADD CONSTRAINT FK_AthleteTeamName FOREIGN KEY TeamName REFERENCES Team (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_AthleteCountryName FOREIGN KEY CountryName REFERENCES Country (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_AthleteSportID FOREIGN KEY SportID REFERENCES Sport (ID) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_AthleteAccomodationName FOREIGN KEY AccomodationName REFERENCES Accomodation (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_AthleteRoomNumber FOREIGN KEY RoomNumber REFERENCES Room (Number) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Results)
ADD CONSTRAINT FK_ResultsCountryName FOREIGN KEY CountryName REFERENCES Country (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_ResultsEventBeginTimeStamp FOREIGN KEY EventBeginTimeStamp REFERENCES Event (BeginTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_ResultsEventEndTimeStamp FOREIGN KEY EventEndTimeStamp REFERENCES Event (EndTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_ResultsVenueName FOREIGN KEY EventVenueName REFERENCES Event (VenueName) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (AccommodationTypes)
ADD CONSTRAINT FK_AccomodationTypesAccomodationName FOREIGN KEY AccomodationName REFERENCES Accomodation (Name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Room)
ADD CONSTRAINT FK_RoomAccomodationName FOREIGN KEY AccomodationName REFERENCES Accomodation (Name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE (Transportation)
ADD CONSTRAINT FK_TransportationAccomodationName FOREIGN KEY AccomodationName REFERENCES Accomodation (Name) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_TransportationEventBeginTimeStamp FOREIGN KEY EventBeginTimeStamp REFERENCES Event (BeginTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_TransportationEventEndTimeStamp FOREIGN KEY EventEndTimeStamp REFERENCES Event (EndTimeStamp) ON UPDATE CASCADE ON DELETE CASCADE
ADD CONSTRAINT FK_TransportationVenueName FOREIGN KEY VenueName REFERENCES Venue (Name) ON UPDATE CASCADE ON DELETE CASCADE;











