DROP TABLE Athlete;

CREATE TABLE IF NOT EXISTS `Athlete` (
	ID INTEGER NOT NULL,
	FirstName VARCHAR(20),
	MiddleName VARCHAR(20),
	LastName VARCHAR(20),
	WeightKg DECIMAL(5, 2) UNSIGNED,
	Sex VARCHAR(10),
	Birthday DATE,
	CountryName VARCHAR(20),
	SportID INTEGER,
	AccomodationName VARCHAR(20),
	RoomNo INTEGER,
    PRIMARY KEY (ID)
);